name: Bump version
on:
  workflow_dispatch:
    inputs:
      versionType:
        description: 'The type of version bump to perform: major, minor, patch'
        required: true
        default: 'patch'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        uses: hennejg/github-tag-action@v4.3.1
        with:
          github_token: ${{ secrets.PAT }}
          default_bump: ${{ github.event.inputs.versionType }} 
